export const TYPES = {
    CREATE_DATA : "CREATE_DATA",
    READ_ALL_DATA : "READ_ALL_DATA",
    //READ_ONE_DATA : "READ_ONE_DATA",
    UPDATE_DATE : "UPDATE_DATE",
    DELETE_DATA : "DELETE_DATA",
    NO_DATA : "NO_DATA",
}